"""empty message

Revision ID: 93efa41f5575
Revises: b801b5dfee23
Create Date: 2019-08-25 21:24:22.681072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93efa41f5575'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'procedural_wait')
    op.alter_column('providers', 'consultation_wait', existing_type=sa.Integer(), type_=sa.Float())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('procedural_wait', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('providers', 'consultation_wait', existing_type=sa.Float(), type_=sa.Integer())
    # ### end Alembic commands ###
